Fix another GCC-16 compile error
The error (which is IMHO due to a compiler bug) si now fixed for GCC-16

cd /build/dune-geometry-2.11.0/build/dune/geometry/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/test-cornerstoragerefwrap.dir/link.txt --verbose=1
/build/dune-geometry-2.11.0/dune/geometry/test/test-localfiniteelementgeometry.cc: In instantiation of 'bool checkLocalFiniteElementGeometry() [with ctype = double; int cdim = 1; Dune::GeometryType::IdType id = (Dune::GeometryType::IdType)1]':
/build/dune-geometry-2.11.0/dune/geometry/test/test-localfiniteelementgeometry.cc:92:85:   required from 'bool checkLocalFiniteElementGeometry() [with ctype = double]'
   92 |   pass &= checkLocalFiniteElementGeometry<ctype, 1, Dune::GeometryTypes::simplex(1)>();
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/build/dune-geometry-2.11.0/dune/geometry/test/test-localfiniteelementgeometry.cc:136:52:   required from here
  136 |   pass &= checkLocalFiniteElementGeometry< double >();
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/build/dune-geometry-2.11.0/dune/geometry/test/test-localfiniteelementgeometry.cc:46:46: error: use of local variable with automatic storage from containing function
   46 |   auto f = [&](Dune::FieldVector<ctype,gt.dim()> const& x) {
      |                                        ~~~~~~^~
/build/dune-geometry-2.11.0/dune/geometry/test/test-localfiniteelementgeometry.cc:27:18: note: 'constexpr const Dune::GeometryType gt' declared here
   27 |   constexpr auto gt = Dune::GeometryType{id};
      |                  ^~